version: '3'
services:
    config:
        build:
            context: ./ifood-config-server
            dockerfile: Dockerfile
        ports:
            - 9090:9090
    eureka:
        build:
            context: ./ifood-eureka-server
            dockerfile: Dockerfile
        ports:
            - 9091:9091
        depends_on:
            - config
    zuul:
        build:
            context: ./ifood-zuul-server
            dockerfile: Dockerfile
        ports:
            - 9092:9092
        depends_on:
            - config
            - eureka
    suggestion:
        build:
            context: ./ifood-suggestion-server
            dockerfile: Dockerfile
        ports:
            - 9093:9093
        depends_on:
            - config
            - eureka
            - zuul
